### ISSUE TITLE
Typing broke compatibility with blender 2.83

### ISSUE THREAD

**Issue by lampysprites** [lampysprites/pribambase#20]
**Reality**
The addon crashes when trying to enable it.

**Expectation**
It should not

**Logs**
```
Read prefs: C:\Users\lampy\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:\Users\lampy\Desktop\blender-2.83.18-windows-x64\2.83\python
Traceback (most recent call last):
  File "C:\Users\lampy\Desktop\blender-2.83.18-windows-x64\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\lampy\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\pribambase\__init__.py", line 32, in <module>
    from .sync import *
  File "C:\Users\lampy\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\pribambase\sync.py", line 22, in <module>
    from aiohttp.web_ws import WebSocketResponse
  File "C:\Users\lampy\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\pribambase\thirdparty\aiohttp-3.8.0-cp39-cp39-win_amd64.whl\aiohttp\__init__.py", line 5, in <module>
    from . import hdrs as hdrs
  File "C:\Users\lampy\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\pribambase\thirdparty\aiohttp-3.8.0-cp39-cp39-win_amd64.whl\aiohttp\hdrs.py", line 13, in <module>
    from typing_extensions import Final
ModuleNotFoundError: No module named 'typing_extensions'

```

**Version info**
- blender 2.83
- Aseprite any
- Pribambase 2.1.1
- OS win64 (any?)

**Additional context**
ouch

**Comment by lampysprites** [comment]
https://stackoverflow.com/questions/50236742/is-there-a-way-to-use-type-hinting-on-back-compatible-code-in-python
