### ISSUE TITLE
Numpy not found error on enable

### ISSUE THREAD

**Issue by argentsileo** [lampysprites/pribambase#22]
**Reality**
On a fresh install of Blender, install the extension and try to enable it. It gives a ModuleNotFoundError and fails to load. Numpy is already installed systemwide.

**Expectation**
An enabled extension.

**Logs**
```
Traceback (most recent call last):
  File "/usr/share/blender/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/argent/.config/blender/3.0/scripts/addons/pribambase/__init__.py", line 31, in <module>
    from .props import *
  File "/home/argent/.config/blender/3.0/scripts/addons/pribambase/props.py", line 29, in <module>
    from .addon import addon
  File "/home/argent/.config/blender/3.0/scripts/addons/pribambase/addon.py", line 91, in <module>
    from .messaging import handle
  File "/home/argent/.config/blender/3.0/scripts/addons/pribambase/messaging/handle.py", line 27, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Version info**
- Blender: 3.0.1
- Aseprite: N/A
- Pribambase: 2.2.1
- OS: Arch Linux

**Comment by lampysprites** [comment]
blender has own python separate from system one, so system packages aren't
available. numpy is a part of the distribution. so please ask your package
maintainers.

anyway it's okay to use blender provided pip, as long as you don't let it
update itself.

**Comment by lampysprites** [comment]
AFK
