### ISSUE TITLE
Websocket failed to send data

### ISSUE THREAD

**Issue by Bionic-Matt** [lampysprites/pribambase#29]
**Reality**
Addon loaded in blender (latest release) and aseprite (v1.3 beta16 64bit)

Sync blender and aseprite successfully (both show connected)

when creating a new sprite via the sprite menu in blender, aseprite console says "appdata/roaming/aseprite/extensions/pribambase/snyc.lua:267 websocket failed to send data

**Logs**

```
Error handling request
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\pribambase\thirdparty\aiohttp-3.8.0-cp310-cp310-win_amd64.whl\aiohttp\web_protocol.py", line 430, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\pribambase\sync.py", line 119, in _receive
    await addon.handlers.process(msg.data)
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\pribambase\messaging\__init__.py", line 143, in process
    msg._parse(mvdata[ID_SIZE:], args)
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\pribambase\messaging\__init__.py", line 107, in _parse
    self.parse(args)
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\pribambase\messaging\handle.py", line 55, in parse
    args.name = self.take_str()
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\pribambase\messaging\__init__.py", line 80, in take_str
    return str(self.take_data(), encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 3083: invalid start byte


```

**Version info**
- for Blender 3,4
- for Aseprite v1.3 beta16
- for Pribambase. if it's installed from source code, please use the commit hash 2.4.1
- OS Windows10 x64

**Additional context**

**Comment by lampysprites** [comment]
Hello! Thanks for the detailed report. i tried to reproduce that with 3.4 and failed, so there seem to be some other factor. Can you please try few other things.

- First, can you please try to un-install ase extension in edit>preferences>extensions and install again.

- Does it work in some other way, like opening existing files; or "Add To Blendfile" button in aseprite.
- Are you trying to create animated sprite?
- Do you see a new sprite appearing is aseprite before the error?
- Does your user folder (C:\Users\???) include non-latin characters? Or name of the image you are trying to create.
- Can you please double check the line number in aseprite error being 267.

**Comment by Bionic-Matt** [comment]
Hi Lampy thanks for your response!

I think something else running on the pc was interfering with the websockets. A fresh install works fine now.

Thanks again!

**Comment by lampysprites** [comment]
Glad that you got it working.

Please let me know if you figure the cause.
