### ISSUE TITLE
Version 2.5.3 throws an error when trying to enable addon in Blender

### ISSUE THREAD

**Issue by gulagkulak** [lampysprites/pribambase#36]
Trying to install the pribambase addon into Blender. When clicking the "enable addon" checkbox, I get an error window. Tried in Blender 2.8 and 3.6.2. Same error in both.

```
Traceback (most recent call last):
  File "/home/gk/Desktop/gamedev/blender-3.6.2-linux-x64/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/gk/.config/blender/3.6/scripts/addons/pribambase/__init__.py", line 32, in <module>
    from .sync import *
  File "/home/gk/.config/blender/3.6/scripts/addons/pribambase/sync.py", line 22, in <module>
    from aiohttp.web_ws import WebSocketResponse
  File "/home/gk/.config/blender/3.6/scripts/addons/pribambase/thirdparty/aiohttp-0.13.1-py3-none-any.whl/aiohttp/__init__.py", line 7, in <module>
    from .connector import *  # noqa
  File "/home/gk/.config/blender/3.6/scripts/addons/pribambase/thirdparty/aiohttp-0.13.1-py3-none-any.whl/aiohttp/connector.py", line 12, in <module>
    from .client import ClientRequest
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen zipimport>", line 170, in find_spec
  File "<frozen importlib._bootstrap>", line 431, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location
  File "<frozen zipimport>", line 229, in get_filename
  File "<frozen zipimport>", line 767, in _get_module_code
  File "<frozen zipimport>", line 696, in _compile_source
  File "/home/gk/.config/blender/3.6/scripts/addons/pribambase/thirdparty/aiohttp-0.13.1-py3-none-any.whl/aiohttp/client.py", line 144
    yield from asyncio.async(resp.release(), loop=loop)
                       ^^^^^
SyntaxError: invalid syntax

```

**Comment by lampysprites** [comment]
Looks like a linux, and those have a running problem of causing environment issues related to blender's python. Which i think is also the case here, since the error happens in the import module, and not this addon.

Perhaps just installing numpy and asyncio python packages in your system will help. Otherwise you have to figure out which interpreter is being used, and how's it different from what current release of blender is built for.

If there's further info about that, I'd be happy to help.

**Comment by gulagkulak** [comment]
I did some googling and the issue seems to be that "async" became a reserved keyword in Python 3.7 and my Blender install is running Python 3.8, so that's why it raises a SyntaxError on that line.

https://stackoverflow.com/questions/51196568/create-task-asyncio-async-syntaxerror-invalid-syntax

Since this error happens in the plugin's thirdparty bundled software, maybe you can upgrade to a newer version of aiohttp that is compatible with Python 3.7? The latest version seems to be 3.8.5, but the bundled thirdparty version is 0.13.1 from 2014.

**Comment by lampysprites** [comment]
Pip decided that's "latest" on linux x64 for some reason..

for now, you can delete that wheel download a new one manually into that folder.

**Comment by lampysprites** [comment]
should work now

**Comment by gulagkulak** [comment]
Confirmed working in Blender 2.8.2 and 3.6. When running in 2.8.2 the "Launch aseprite" button does not show up and the following error is displayed in terminal:

```
Traceback (most recent call last):
  File "/home/elver/.config/blender/2.82/scripts/addons/pribambase/ui.py", line 165, in draw
    layout.operator("pribambase.launch", icon='BRUSHES_ALL')
TypeError: UILayout.operator(): error with keyword argument "icon" -  enum "BRUSHES_ALL" not found in ('NONE', 'QUESTION', 'ERROR', ......... )
```

But the plugin itself is still functional.

Thanks for the quick fix! :)
